### ISSUE TITLE
Leapp 8to9 - Old bootloader entries should be cleaned up after el8 kernels are removed

### ISSUE THREAD

**Issue by bparry02** [redhat-cop/infra.leapp#263]
After upgrading the infra.leapp role to 1.6.0, I'm getting a failure on this check for 8to9:

````
TASK [infra.leapp.upgrade : leapp-post-upgrade | No previous RHEL kernels are present in /boot/loader/entry files] ***
fatal: [east-leapp8to9-x86]: FAILED! =>
... snip and reformat...
cmd: grep -r ".el8" "/boot/loader/entries/"
stdout: /boot/loader/entries/ffffffffffffffffffffffffffffffff-4.18.0-553.40.1.el8_10.x86_64.conf:title Red Hat Enterprise Linux (4.18.0-553.40.1.el8_10.x86_64) 8.10 (Ootpa)
... snip
````

After investigating, this seems to be happening on a brand-new test instance, which only has two el8 kernels installed--the original kernel from the image, and one after the update to latest before leapp analysis. It appears that removing the first kernel during the `Remove old RHEL packages` task is not cleaning up the bootloader entries properly. However, when the kernel is updated 3+ times (e.g. for a host that has been running for a while and updating regularly), there is no error from old bootloader entries after leapp. Maybe kernels are cleaned up differently on update vs uninstall? I don't think this is an issue with the role or leapp.

To help mitigate this strange behavior, I suggest adding logic to remove the bootloader entries for the original RHEL version. This can be done via grubby command line or maybe the [fedora.linux_system_roles.bootloader](https://github.com/linux-system-roles/bootloader) role could help.

````
[root@ip-172-31-16-254 ~]# grubby --remove-kernel=/boot/vmlinuz-4.18.0-553.40.1.el8_10.x86_64
[root@ip-172-31-16-254 ~]# grubby --remove-kernel=/boot/vmlinuz-0-rescue-ffffffffffffffffffffffffffffffff
````

Or:

````
... TBD tasks to search for bootloader entries for previous RHEL version

- name: Remove bootloader entry
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.bootloader
  vars:
    bootloader_settings:
      - kernel:
          title: "Red Hat Enterprise Linux (0-rescue-ffffffffffffffffffffffffffffffff) 8.10 (Ootpa)"
        state: absent
    bootloader_reboot_ok: true  # if needed?
````

In the meantime I can add the `remove_old_rhel_packages: false` flag to these hosts as a workaround.

**Comment by swapdisk** [comment]
Issue reproduced and root cause identified. What we found is that there's a regression in RHEL 9 (and 10) where so called "fake" BLS configs don't get cleaned up when kernel packages are uninstalled. Fake BLS configs refer to the files under the `/boot/loader/entries` directory that have the "ffff..." prefix. That prefix normally matches the contents of the `/etc/machine-id` file, but since that file doesn't exist in the AMI images, the BLS configs in the AMI use the fake prefix.

There's already an issue open with the RHEL team for this at [RHEL-83915](https://issues.redhat.com/browse/RHEL-83915) and the fix has been committed upstream for the RHEL 9 grub2 packages [here](https://gitlab.com/redhat/centos-stream/rpms/grub2/-/commit/4946e4fb2204afd7f17696904854abbb0ddc1840), so we should expect the solution will be coming soon.

In the meantime, let's keep this issue open for awareness and tracking.

**Comment by rev138** [comment]
I can't see the ticket referenced above but I can report this is still an issue with 9 -> 10

**Comment by swapdisk** [comment]
@rev138, thank you for reporting your observations. The updated RHEL 9 grub2 packages still aren't out and will probably  with come with the 9.7 release.

However, your situation is a little different and the upcoming fix to grub2 will not solve it. The best way to handle your issue would be to clean up the "orphaned" entries when VMs are deployed, or better yet, when the templates are built. It's best practice for OS images or templates to be built with "fake" BLS configs using the "ffff..." prefix and with the `/etc/machine-id` file removed.

In the meantime, do the task in your pre-remediation playbook and call it a fail-fast win!

**Comment by spetrosi** [comment]
This has been fixed as part of https://github.com/redhat-cop/infra.leapp/pull/297
Indeed, there is a bug in some environments where removing RPMs that installed old kernels does not remove kernel paths. The above PR works around this bug by manually removing outdated kernels if they are found.
